name: Node.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Aggregate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gecko-dev
      uses: actions/checkout@v4
      with:
          repository: mozilla/gecko-dev
          path: gecko-dev
          sparse-checkout: "browser/themes"
