name: Node.js

on:
  push:
    branches: [ "feature/aggregate-action"]

jobs:
  Aggregate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gecko-dev
      uses: actions/checkout@v4
      with:
          repository: mozilla/gecko-dev
          path: ./gecko-dev
          sparse-checkout: "browser/themes"
    - name: Run script
      run: python scripts/aggregate.py --path "./gecko-dev"