name: Aggregate

on:
  push:
    branches: [ "feature/gecko-dev-branch" ]
  schedule:
    - cron: "0 0 1 * *" 

jobs:
  Aggregate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: [beta, master, release]
    steps:
    - name: Checkout firefox-css
      uses: actions/checkout@v4
      with:
          path: firefox-css
    - name: Checkout gecko-dev
      uses: actions/checkout@v4
      with:
          path: gecko-dev
          ref: ${{ matrix.source }}
          repository: mozilla/gecko-dev
          sparse-checkout: "browser/themes"
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version:  '3.12'
    - name: Install aggregate.requirements.txt
      working-directory: firefox-css
      run: pip install -r scripts/aggregate.requirements.txt
    - name: Run script
      working-directory: firefox-css
      run: python scripts/aggregate.py --input "gecko-dev" --output "./completions/${{ matrix.source }}"
  Commit:
    - name: Checkout firefox-css
      uses: actions/checkout@v4
      with:
          path: firefox-css
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit changes
      working-directory: firefox-css
      run: |
        git config --global user.name 'Firefox CSS Aggregate GitHub Action'
        git config --global user.email 'wrightci01s@gmail.com'
        git add .
        git diff-index --quiet HEAD || git commit -m "Auto updating completions"
        git push
