name: Aggregate

on:
  push:
    branches: [ "feature/aggregate-action"]

jobs:
  Aggregate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout firefox-css
      uses: actions/checkout@v4
      with:
          path: firefox-css
    - name: Checkout gecko-dev
      uses: actions/checkout@v4
      with:
          repository: mozilla/gecko-dev
          path: gecko-dev
          sparse-checkout: "browser/themes"
    - name: Run script
      uses: actions/setup-python@v5
      with:
        python-version:  '3.12'
      working-directory: firefox-css
      run: python scripts/aggregate.py --path "gecko-dev"